### ISSUE TITLE
Readme: Webhooks

### ISSUE THREAD

**Issue by wawhal** [hasura/android-sdk#9]
There should be some instructions in the readme regarding the permission webhook that one needs to create in order to use the Filestore service.

**Comment by coco98** [comment]
@wawhal https://docs.hasura.io/0.13/ref/hasura-microservices/filestore/index.html
Does that help, or do you want something more specific? 

PS: Sidenote - we're maintaining a central list of issues at https://github.com/hasura/support/issues. In the future, it would be great if you filed issues such as this there. :)
